-- ============================================================
-- Basith's Radar — Seed Data (15 realistic events)
-- Run AFTER schema.sql
-- ============================================================

INSERT INTO events (title, org, type, location, is_free, application_deadline, event_date, description, apply_url, source_url, tags, why_read, is_manually_added)
VALUES
  (
    'Smart India Hackathon 2026 Internal Round',
    'MGIT / AICTE',
    'hackathon',
    'MGIT, Hyderabad',
    true,
    (CURRENT_DATE + INTERVAL '12 days')::DATE,
    (CURRENT_DATE + INTERVAL '20 days')::DATE,
    'National-level hackathon hosted by AICTE. Internal round at MGIT to select teams for the national finals. Build solutions for real government problem statements.',
    'https://sih.gov.in',
    'https://sih.gov.in',
    ARRAY['hackathon', 'government', 'national', 'MGIT'],
    'SIH internal round — winning gets you national stage. Apply with your team now.',
    false
  ),
  (
    'T-Hub AI Product Innovation Summit 2026',
    'T-Hub Hyderabad',
    'summit',
    'T-Hub Phase 2, Hyderabad',
    true,
    (CURRENT_DATE + INTERVAL '5 days')::DATE,
    (CURRENT_DATE + INTERVAL '14 days')::DATE,
    'Two-day summit bringing together AI founders, product leaders, and investors. Features keynotes from Google DeepMind India and Microsoft Research.',
    'https://thub.telangana.gov.in/events',
    'https://thub.telangana.gov.in/events',
    ARRAY['AI', 'summit', 'hyderabad', 'T-Hub', 'founders'],
    'Google DeepMind India keynote + networking with funded AI startups in Hyderabad.',
    false
  ),
  (
    'IIIT-H Research Open Day: NLP & Vision',
    'IIIT Hyderabad',
    'workshop',
    'IIIT Hyderabad, Gachibowli',
    true,
    (CURRENT_DATE + INTERVAL '3 days')::DATE,
    (CURRENT_DATE + INTERVAL '10 days')::DATE,
    'Open day for undergrads to interact with IIIT-H research labs. Sessions on NLP, computer vision, and robotics. Lab visits included.',
    'https://iiit.ac.in/events',
    'https://iiit.ac.in/events',
    ARRAY['research', 'NLP', 'vision', 'IIIT-H', 'free'],
    'Direct access to IIIT-H NLP/vision labs — great for research internship leads.',
    false
  ),
  (
    'Google Developer Student Clubs Solution Challenge Kickoff',
    'GDSC MGIT',
    'workshop',
    'MGIT, Hyderabad',
    true,
    (CURRENT_DATE + INTERVAL '8 days')::DATE,
    (CURRENT_DATE + INTERVAL '15 days')::DATE,
    'Kickoff workshop for Google''s global Solution Challenge. Learn to build with Google technologies. Teams from MGIT will represent in regional finals.',
    'https://developers.google.com/community/gdsc-solution-challenge',
    'https://developers.google.com/community/gdsc-solution-challenge',
    ARRAY['Google', 'GDSC', 'solution-challenge', 'MGIT', 'global'],
    'Google Solution Challenge — global competition with mentorship from Google engineers.',
    false
  ),
  (
    'Microsoft Imagine Cup 2026 — India Qualifier',
    'Microsoft India',
    'hackathon',
    'Online + Hyderabad Hub',
    true,
    (CURRENT_DATE + INTERVAL '18 days')::DATE,
    (CURRENT_DATE + INTERVAL '35 days')::DATE,
    'Microsoft''s flagship student tech competition. AI-first track this year with Azure OpenAI integration. Winners get mentorship from Microsoft CTOs and travel to US finals.',
    'https://imaginecup.microsoft.com',
    'https://imaginecup.microsoft.com',
    ARRAY['Microsoft', 'AI', 'Azure', 'hackathon', 'global'],
    'Azure OpenAI track — Microsoft CTO mentorship + US finals trip for winners.',
    false
  ),
  (
    'MLH Global Hack Week: AI Edition',
    'Major League Hacking',
    'hackathon',
    'Online',
    true,
    (CURRENT_DATE + INTERVAL '2 days')::DATE,
    (CURRENT_DATE + INTERVAL '7 days')::DATE,
    'Week-long hackathon series focused on AI. Daily mini-challenges and workshops. Build AI tools and compete for swag, cash prizes, and recruiter attention.',
    'https://mlh.io/seasons/2026/events',
    'https://mlh.io',
    ARRAY['MLH', 'AI', 'online', 'hackathon', 'weekly'],
    'MLH AI week — daily challenges, recruiter visibility, and a strong resume boost.',
    false
  ),
  (
    'Devfolio ETHIndia Hackathon',
    'Devfolio',
    'hackathon',
    'Bangalore (Hybrid)',
    true,
    (CURRENT_DATE + INTERVAL '22 days')::DATE,
    (CURRENT_DATE + INTERVAL '30 days')::DATE,
    'India''s biggest blockchain hackathon. $1M+ in prizes. AI + Web3 intersection track added this year.',
    'https://ethindia.co',
    'https://devfolio.co/hackathons',
    ARRAY['blockchain', 'web3', 'AI', 'devfolio', 'prize'],
    '$1M prize pool — AI+Web3 track is new and undersubscribed. Good odds.',
    false
  ),
  (
    'Unstop PM Bootcamp: AI Product Management',
    'Unstop x ProductHood',
    'workshop',
    'Online',
    true,
    (CURRENT_DATE + INTERVAL '6 days')::DATE,
    (CURRENT_DATE + INTERVAL '13 days')::DATE,
    '3-day intensive bootcamp on AI product management. Covers PRD writing for AI features, metrics for LLM products, and case studies from Notion AI and GitHub Copilot.',
    'https://unstop.com',
    'https://unstop.com',
    ARRAY['PM', 'AI', 'product-management', 'bootcamp', 'online'],
    'AI PM frameworks — covers Notion AI and Copilot case studies. Directly usable.',
    false
  ),
  (
    'Anthropic Developer Day India',
    'Anthropic',
    'summit',
    'Bangalore (Hybrid/Streaming)',
    true,
    (CURRENT_DATE + INTERVAL '25 days')::DATE,
    (CURRENT_DATE + INTERVAL '32 days')::DATE,
    'Anthropic''s first Indian developer event. Claude API deep dives, agent architectures, constitutional AI, and a live Q&A with the research team.',
    'https://anthropic.com/events',
    'https://anthropic.com/events',
    ARRAY['Anthropic', 'Claude', 'AI', 'developer', 'LLM'],
    'Anthropic''s India debut — live access to the Claude research team. Don''t miss.',
    false
  ),
  (
    'NIT Warangal Techfest: HackWarangal',
    'NIT Warangal',
    'hackathon',
    'NIT Warangal, Telangana',
    true,
    (CURRENT_DATE + INTERVAL '9 days')::DATE,
    (CURRENT_DATE + INTERVAL '17 days')::DATE,
    '24-hour hackathon during NIT-W''s annual techfest. Problem statements in AI, robotics, and sustainability. ₹2L prize pool.',
    'https://nitw.ac.in/events',
    'https://nitw.ac.in/events',
    ARRAY['NIT-W', 'hackathon', 'AI', 'robotics', 'prize'],
    '₹2L prize + NIT-W network. 90km from Hyderabad — worth the trip.',
    false
  ),
  (
    'n8n Automation Bootcamp India 2026',
    'n8n Community India',
    'workshop',
    'Online',
    true,
    (CURRENT_DATE + INTERVAL '4 days')::DATE,
    (CURRENT_DATE + INTERVAL '11 days')::DATE,
    'Community-run bootcamp on n8n workflow automation. Advanced topics: AI agent nodes, webhook integrations, self-hosting on Railway/Render.',
    'https://community.n8n.io',
    'https://community.n8n.io',
    ARRAY['n8n', 'automation', 'AI-agents', 'workshop', 'free'],
    'n8n advanced nodes + AI agents — directly applicable to your automation projects.',
    false
  ),
  (
    'OpenAI DevDay India Watch Party + Hackathon',
    'AWS User Group Hyderabad',
    'hackathon',
    'AWS Office, Hyderabad',
    true,
    (CURRENT_DATE + INTERVAL '1 days')::DATE,
    (CURRENT_DATE + INTERVAL '4 days')::DATE,
    'Watch OpenAI DevDay live + immediate 6-hour hackathon using the newly announced APIs. Great for meeting the Hyderabad AI community.',
    'https://www.meetup.com/awsughyderabad',
    'https://www.meetup.com/awsughyderabad',
    ARRAY['OpenAI', 'GPT', 'AWS', 'hyderabad', 'hackathon', 'urgent'],
    'Deadline TOMORROW — OpenAI new API hackathon + Hyderabad AI community meetup.',
    false
  ),
  (
    'Dare2Compete PM Case Competition: AI Tools Edition',
    'Dare2Compete',
    'conference',
    'Online',
    true,
    (CURRENT_DATE + INTERVAL '15 days')::DATE,
    (CURRENT_DATE + INTERVAL '22 days')::DATE,
    'PM case competition analyzing real AI product decisions. Cases from companies like Perplexity, Linear, and Figma AI.',
    'https://dare2compete.com',
    'https://dare2compete.com',
    ARRAY['PM', 'case-competition', 'AI', 'Perplexity', 'online'],
    'PM case on Perplexity''s growth strategy — great for your PM portfolio.',
    false
  ),
  (
    'YC AI Residency Application Open (S26)',
    'Y Combinator',
    'workshop',
    'San Francisco (Remote OK)',
    true,
    (CURRENT_DATE + INTERVAL '30 days')::DATE,
    (CURRENT_DATE + INTERVAL '90 days')::DATE,
    'Y Combinator''s AI residency program for researchers and builders. Remote-friendly. $500K in compute credits included.',
    'https://ycombinator.com/apply',
    'https://ycombinator.com/apply',
    ARRAY['YC', 'residency', 'AI', 'funding', 'global'],
    'YC AI residency — $500K compute + YC network. Apply with Janus Bridge.',
    false
  ),
  (
    'Townscript: Hyderabad AI Builders Meetup',
    'Hyderabad AI Community',
    'workshop',
    'Koramangala Community Hall, Hyderabad',
    true,
    (CURRENT_DATE + INTERVAL '7 days')::DATE,
    (CURRENT_DATE + INTERVAL '12 days')::DATE,
    'Monthly meetup for AI builders in Hyderabad. Lightning talks (15 min each), demo tables, and open networking. Anyone building AI products can present.',
    'https://townscript.com',
    'https://townscript.com',
    ARRAY['meetup', 'AI', 'hyderabad', 'builders', 'networking'],
    'Monthly Hyderabad AI builder meetup — present your projects to 200+ local builders.',
    false
  );
