import { NextRequest, NextResponse } from 'next/server';
import { sendWhatsAppMessage } from '@/lib/whatsapp';

// Bot output signatures to prevent recursive loops
const BOT_SIGNATURES = [
  '☀️ *Hackey',
  '🌙 *Hackey',
  '☀️ *Basith',
  '🌙 *Basith',
  '📋 *Your Radar',
  '📋 *Hackey Status',
  '✅ *Saved',
  '🎉 *Marked',
  '🎉 *Congratulations',
  '🗑 Removed event',
  '⏸ *Notifications Paused',
  '▶️ *Notifications Resumed',
  '📍 *Preferences Updated',
  '🇮🇳 *Preferences Updated',
  '🆓 *Preferences Updated',
  '✨ *More Upcoming',
  '👋 *Hackey Commands',
  '👋 *Basith’s Radar',
  '🔔 *Application',
  '📅 *Event happening',
  '— Hackey ⚡',
  '— Basith’s Radar',
  '⚡ *Hackey',
  '⚡ *Basith’s Radar',
  '☁️ *Cloud 24/7',
];

export async function POST(req: NextRequest) {
  try {
    const rawBody = await req.json();

    const remoteJid = String(rawBody?.data?.key?.remoteJid || '');

    // 1. HARD RULE: Never reply to group chats
    if (remoteJid.endsWith('@g.us')) {
      return NextResponse.json({ status: 'ignored', reason: 'Group message ignored' });
    }

    let senderPhone = '';
    let incomingText = '';

    if (remoteJid) {
      senderPhone = remoteJid.replace('@s.whatsapp.net', '').replace(/\D/g, '');
      incomingText = String(
        rawBody.data?.message?.conversation ||
        rawBody.data?.message?.extendedTextMessage?.text ||
        ''
      ).trim();
    } else if (rawBody?.From) {
      senderPhone = String(rawBody.From).replace('whatsapp:', '').replace(/\D/g, '');
      incomingText = String(rawBody.Body || '').trim();
    } else if (rawBody?.phone && rawBody?.message) {
      senderPhone = String(rawBody.phone).replace(/\D/g, '');
      incomingText = String(rawBody.message).trim();
    }

    if (!senderPhone || !incomingText) {
      return NextResponse.json({ status: 'ignored', reason: 'Empty sender or text' });
    }

    // 2. Loop prevention: Ignore messages that were generated by the bot itself
    const isBotOutput = BOT_SIGNATURES.some((sig) => incomingText.startsWith(sig) || incomingText.includes(sig));
    if (isBotOutput) {
      return NextResponse.json({ status: 'ignored', reason: 'Bot output signature ignored' });
    }

    const normalizedCmd = incomingText.toUpperCase().trim();
    let replyText = '';

    // 3. STRICT COMMAND ROUTING: Only respond if text matches a recognized command!
    // (Casual messages like "hi", "bro", "where are you" are silently ignored)
    if (normalizedCmd.startsWith('SAVE')) {
      const num = normalizedCmd.replace('SAVE', '').trim() || '1';
      replyText = `✅ *Saved Event #${num} to Radar!*\n\n📌 *Smart India Hackathon 2026 Internal Round*\n⏰ Reminders are active (7d, 3d, 1d & day-of alert).\n\n🔗 Apply: https://sih.gov.in`;
    } else if (normalizedCmd.startsWith('DONE')) {
      const num = normalizedCmd.replace('DONE', '').trim() || '1';
      replyText = `🎉 *Marked Event #${num} as Applied!*\n\n📌 *Smart India Hackathon 2026*\nWe’ll ping you on the event morning at 8:00 AM IST!`;
    } else if (normalizedCmd.startsWith('UNSAVE') || normalizedCmd.startsWith('SKIP')) {
      replyText = `🗑 Removed event from your saved radar and cancelled upcoming alerts.`;
    } else if (normalizedCmd === 'STATUS' || normalizedCmd.startsWith('STATUS')) {
      replyText = `📋 *Your Radar Status*\n\n1. *Smart India Hackathon 2026* [⏳ 3 days left]\n2. *T-Hub AI Innovation Summit* [📅 Sep 15]\n\nNotifications: 🟢 Active (8:00 AM & 7:00 PM Briefings)`;
    } else if (normalizedCmd === 'PAUSE') {
      replyText = `⏸ *Notifications Paused*\n\nYou will not receive briefings or deadline alerts. Reply *RESUME* anytime to reactivate.`;
    } else if (normalizedCmd === 'RESUME') {
      replyText = `▶️ *Notifications Resumed!*\n\nYour morning (8:00 AM) & evening (7:00 PM) AI/PM briefings are back on.`;
    } else if (normalizedCmd.includes('SET HYDERABAD')) {
      replyText = `📍 *Preferences Updated:* Prioritizing Hyderabad campus & tech events (T-Hub, IIIT-H, MGIT).`;
    } else if (normalizedCmd.includes('SET PAN INDIA')) {
      replyText = `🇮🇳 *Preferences Updated:* Tracking India-wide hackathons and national competitions.`;
    } else if (normalizedCmd.includes('FREE ONLY')) {
      replyText = `🆓 *Preferences Updated:* Filtering only free opportunities & competitions.`;
    } else if (normalizedCmd === 'MORE' || normalizedCmd.startsWith('MORE')) {
      replyText = `✨ *More Upcoming Opportunities*\n\n1. *IIIT-H Research Open Day: NLP & Vision*\n→ Direct access to research labs for internships.\nApply: https://iiit.ac.in/events\n\n2. *Google Solution Challenge 2026*\n→ Global mentorship & Gemini API compute.\nApply: https://developers.google.com\n\nReply *SAVE 1* or *SAVE 2* to track.`;
    } else if (normalizedCmd === 'HELP' || normalizedCmd === 'COMMANDS') {
      replyText = `👋 *Basith’s Radar Commands*\n\n• *STATUS* — view your saved events & deadlines\n• *SAVE <num>* — save event from latest brief\n• *DONE <num>* — mark as applied\n• *MORE* — get more opportunities\n• *PAUSE* / *RESUME* — toggle alerts\n• *SET HYDERABAD* / *SET PAN INDIA*`;
    } else {
      // Normal casual conversation -> SILENTLY IGNORE (never spam contacts)
      return NextResponse.json({ status: 'ignored', reason: 'Not a recognized command' });
    }

    // Send instant WhatsApp reply back to the sender
    await sendWhatsAppMessage({
      to: senderPhone,
      body: replyText,
    });

    return NextResponse.json({ status: 'success', replied: true, replyText });
  } catch (err: unknown) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    console.error('WhatsApp Webhook error:', errorMsg);
    return NextResponse.json({ error: errorMsg }, { status: 500 });
  }
}
